# Generated by Django 5.2.7 on 2025-12-17 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),
                #('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                #('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
